- func: "testlm"
  filename: "testlm"
  digits: 8
  config: /autograder/source/config/config.prob.yaml
  preload_usr: /autograder/source/config/preload.baseonly.R
  preload_sol: /autograder/source/config/preload.baseonly.R
