- args: /autograder/source/args/test.1.args
  maxtime: 3
- args: /autograder/source/args/test.2.args
  maxtime: 3
- args: /autograder/source/args/test.3.args
  maxtime: 3
- args: /autograder/source/args/test.4.args
  maxtime: 3
- args: /autograder/source/args/test.5.args
  maxtime: 3
- args: /autograder/source/args/test.6.args
  maxtime: 3
- args: /autograder/source/args/test.7.args
  maxtime: 3
- args: /autograder/source/args/test.8.args
  maxtime: 3
- args: /autograder/source/args/test.9.args
  maxtime: 3
- args: /autograder/source/args/test.10.args
  maxtime: 3
